---
title: "Untitled"
author: "Julin N Maloof"
date: "11/22/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Chapter 2 Problems 1, 3, 4.  (For problem 4, focus your answers on biology), 6

## 2.1

(a).  A flexible model should perform well here.  With a large n the variance due to training set differences should be low and the flexible model will allow reduced bias.

(b). inflexible will be better here.  Flexible models would likely overfit this data set leading to high variance.

(c).  flexible models will have an easier time fitting this; inflexible models will have high bias.

(d). inflexible is better, less likely to get thrown off by an outlier.

## 2.3

(b) 

* the irreducible error is exactly that; the inherent error that can't be fit as a funciton of the predictors, so it stays the same.
* Test error is U-shaped because with too inflexible a model the bias is high and with a highly flexible model the variance is high (overfitting).
* Training and Bias go down with increased flexibility because the training set is fit better and better.
* Variance goes up because of the overfitting problem.

## 4

(a)

* plants as being drought tolerant or not, based on genotype (or gene expression).  Prediction (or perhaps both).

* DNA sequence as being coding or non-coding (Prediction).

* genes as being involved in a process


(b)

* growth as a function of time and treatment.  

* gene expression as a function of time and treatment

* phenotype as a function of genotype.

(c)

* genes based on co-expression.  response = gene   expression, predictor could be time or genotype + treatment.  Inference.

* plants as belonging to particular populations.  maybe no response.  predictor is genotype at different loci. Inference.

## 6

Parametric assume a form of the function and then fits the parameters.  Non-parametric methods do not assume a form of the function.

Parametric models are easier to interpret (make inferences from) whereas parametric may be better predictors.